import turtle




screen = turtle.Screen()


screen.setup(800, 800)


screen.bgcolor('Cornflower blue')
t = turtle.Turtle()
t.showturtle()
t2 = turtle.Turtle()
t2.showturtle()
t3 = turtle.Turtle()
t3.showturtle()
t3.hideturtle()


t.hideturtle()
t2.hideturtle()

t.pencolor("black")

t.speed(2000)


t2.penup()
t2.goto(0, 100)
t2.pendown()
t3.penup()
t3.goto(0, 200)
t.penup()
t.goto(0, 50)
t.pendown()
t.write("All About Me", font=("arial", 30, "bold"), align="center")
t.penup()
t.goto(0, -50)
t.pendown()
t.write("Patrick Ault", font=("arial", 30, "bold"), align="center")

t.penup()
t.goto(0,-200)
t.pendown()
t.color("Purple")
t.setheading(0)
t.begin_fill()
t.circle(50)
t.end_fill()


enter = input("press enter to begin")
t.showturtle()
t.clear()
t.pencolor("black")
screen.bgcolor('green')
t.penup()
t.goto(0,250)
t.write("My favorite food", font=("arial", 30, "bold"), align="center")


turtle.addshape("Grilledchicken.gif")
t.shape("Grilledchicken.gif")
t.goto(150,150)
a = t.stamp()
t.hideturtle()
t.goto(150,200)
t.write("Chicken", font=("arial", 30, "bold"), align="center")


turtle.addshape("Pizza.gif")
t.shape("Pizza.gif")
t.goto(0,0)
b = t.stamp()
t.goto(0,50)
t.write("Pizza", font=("arial", 30, "bold"), align="center")
turtle.addshape("Crablegs.gif")
t.shape("Crablegs.gif")
t.goto(-150,150)
c = t.stamp()
t.goto(0,0)
t.goto(-150,200)
t.write("Crab Legs", font=("arial", 30, "bold"), align="center")

t.penup()
t.goto(-50,-100)
t.pendown()
t.fillcolor("Yellow")
t.begin_fill()
t.forward(100)
t.right(90)
t.forward(100)
t.right(90)
t.forward(100)
t.right(90)
t.forward(100)
t.right(90)
t.end_fill()



enter = input("press enter to begin")
t.clear()
t.clearstamps()
screen.bgcolor('orange')

t.penup()
t.goto(0,300)
t.write("My favorite hobbies", font=("arial", 30, "bold"), align="center")
t.pencolor("black")
turtle.addshape("Fishing.gif")
t.shape("Fishing.gif")
t.goto(150,150)
a = t.stamp()
t.hideturtle()
t.goto(150,200)
t.write("Fishing", font=("arial", 30, "bold"), align="center")


turtle.addshape("Basketball.gif")
t.shape("Basketball.gif")
t.goto(0,0)
b = t.stamp()
t.goto(0,50)
t.write("Basketball", font=("arial", 30, "bold"), align="center")
turtle.addshape("Golf.gif")
t.shape("Golf.gif")
t.goto(-150,-150)
c = t.stamp()
t.goto(0,0)
t.goto(-150,-100)
t.write("Golf", font=("arial", 30, "bold"), align="center")

turtle.addshape("Travel.gif")
t.shape("Travel.gif")
t.goto(-150,150)
a = t.stamp()
t.goto(-150,150)
t.hideturtle()
t.goto(-150,200)
t.write("Traveling", font=("arial", 30, "bold"), align="center")

t.penup()
t.goto(150,-200)
t.pendown()
t.fillcolor('blue')
t.begin_fill()
t.setheading(45)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.setheading(0)
t.end_fill()


enter = input("press enter to begin")
t.clear()
t.clearstamps()
screen.bgcolor('dark grey')
t.pencolor("black")
t.penup()
t.goto(0,300)
t.write("My favorite movie", font=("arial", 30, "bold"), align="center")

turtle.addshape("Happy.gif")
t.shape("Happy.gif")
t.goto(-150,150)
a = t.stamp()
t.goto(-150,150)
t.hideturtle()
t.goto(-150,200)
t.write("Happy Gilmore", font=("arial", 30, "bold"), align="center")

turtle.addshape("Putting.gif")
t.shape("Putting.gif")
t.goto(150,150)
a = t.stamp()
t.hideturtle()
t.goto(150,200)

t.penup()
t.goto(-50,100)
t.pendown()
t.fillcolor("purple")
t.begin_fill()
t.goto(50,100)
t.goto(0,200)
t.goto(-50,100)
t.end_fill()
t.penup()
t.goto(-225,0)

enter = input("press enter to begin")
t.clear()
t.clearstamps()
screen.bgcolor('dodger blue')
t.penup()
t.goto(0,300)
t.write("My favorite sport", font=("arial", 30, "bold"), align="center")
t.pencolor("black")
turtle.addshape("Lebron.gif")
t.shape("Lebron.gif")
t.goto(0,150)
a = t.stamp()
t.goto(0,150)
t.hideturtle()
t.goto(0,200)
t.write("Basketball", font=("arial", 30, "bold"), align="center")

turtle.addshape("Peter.gif")
t.shape("Peter.gif")
t.goto(0,-150)
a = t.stamp()
t.hideturtle()
t.goto(150,200)
t.penup()
t.goto(-75,50)
t.pendown()
t.fillcolor("red")
t.begin_fill()
t.forward(150)
t.right(90)
t.forward(100)
t.right(90)
t.forward(150)
t.right(90)
t.forward(100)
t.right(90)
t.end_fill()


turtle.done()







